### ISSUE TITLE
GetObserver error when checking array[1]

### ISSUE THREAD

**Issue by Apcio** [jdanyow/aurelia-computed#1]
Hi.
How to correctly observe arrays ?

srcipt.js:

``` javascript
/*jshint curly: true, es5: true, debug: true, esnext: true, moz: true, browser: true, devel: true*/
import {computedFrom} from 'aurelia-framework';

export class Welcome{
   constructor (){
      this.tablica = ["Ole1", "Ole2"];
   }

   get WezWartoscTablicy2() {
      return this.tablica[1];
   }
}
```

Html:

``` html
<template>
       <div>Tutaj będe testował bind do tablicy statycznie:</div>
       <br>
       <div>nr1 ${tablica[0]}, a nr2 ma wartość: <span innerHTML.bind="WezWartoscTablicy2"></span></div>
       <label>tablica[0]: </label><input value.bind="tablica[0]">
       <label>tablica[1]: </label><input value.bind="tablica[1]">
    </form>
</template>
```

Error:

<pre>
TypeError: Cannot read property 'getObserver' of undefined
    at AccessKeyedObserver.updatePropertySubscription (http://localhost:9000/jspm_packages/github/aurelia/binding@0.7.2/access-keyed-observer.js:47:56)
    at new AccessKeyedObserver (http://localhost:9000/jspm_packages/github/aurelia/binding@0.7.2/access-keyed-observer.js:35:16)
    at AccessKeyed.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.7.2/ast.js:471:26)
    at GetterObserver.subscribe (http://localhost:9000/jspm_packages/github/jdanyow/aurelia-computed@0.2.0/getter-observer.js:42:36)
    at Binding.bind (http://localhost:9000/jspm_packages/github/aurelia/binding@0.7.2/binding-expression.js:73:53)
    at View.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.12.0/view.js:63:25)
    at RouterView.swap (http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.13.0/router-view.js:78:45)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.9.0/navigation-context.js:84:33
    at Array.forEach (native)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.9.0/navigation-context.js:83:24
</pre>

**Comment by jdanyow** [comment]
You cannot two-way bind to an element in an array:  `<input value.bind="tablica[1]">`.  Two-way binding requires an object property.

**Comment by Apcio** [comment]
I removed And have only that:

```
<template>
   <div>nr1 ${tablica[0]}, a nr2 ma wartość: ${WezWartoscTablicy2}</div>
</template>
```

But the error is showed again. How can I work with arrays ?

**Comment by jdanyow** [comment]
hmmm- I tested that locally and it worked.  Which interpolation binding is causing the problem?  Is it `${tablica[0]}` or `${WezWartoscTablicy2}` or both?

Does it work if you remove the accent characters- we have an open issue related to those:  `<div>nr1 ${tablica[0]} ${WezWartoscTablicy2}</div>`

**Comment by Apcio** [comment]
``` html
<template>
       <div>nr1 ${tablica[0]}</div>
</template>
```

This worked and show me a value: 
![image](https://cloud.githubusercontent.com/assets/11940927/8085369/127c56f8-0f90-11e5-8c97-a23fa823b470.png)

![image](https://cloud.githubusercontent.com/assets/11940927/8085393/36f05c46-0f90-11e5-8ac2-05ae357ff4b0.png)

Aurelia-Skeleton v 0.14 and latest Aurelia-Computed.

/////

I removed get keyword, and then interpolate string as  function, and it works:

```
<div>nr1 ${tablica[0]} nr2 ${tabl()}</div>

tabl() {
      return this.tablica[1];
   }
```

**Comment by Apcio** [comment]
I think, I can close this. There shouldn't be more problems with arrays, when I understand better bindable system.
