### ISSUE TITLE
truthy check before function call not working

### ISSUE THREAD

**Issue by JeroenVinke** [jdanyow/aurelia-computed#6]
This code:

```
get isValidated() {
    return this.user && this.user.isValidated();
  }
```

with this function in the user class:

```
isValidated() {
    return true;
  }
```

results in this error:

```
ERROR [app-router] TypeError: Cannot read property 'isValidated' of undefined
    at ensureFunctionFromMap (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:2059:19)
    at CallMember.evaluate (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:1369:14)
    at CallMember.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:1407:21)
    at Binary.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:1571:34)
    at GetterObserver.subscribe (http://localhost:9000/jspm_packages/github/jdanyow/aurelia-computed@0.5.1/getter-observer.js:39:32)
    at new CompositeObserver (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:877:46)
    at Conditional.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.8.6/aurelia-binding.js:1129:20)
    at InterpolationBinding.connect (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.14.0/aurelia-templating-binding.js:460:29)
    at InterpolationBinding.bind (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.14.0/aurelia-templating-binding.js:403:14)
    at View.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.14.1/aurelia-templating.js:725:21)
```

and the error is gone when you disable aurelia-computed (in main.js).

Test repo is here: https://github.com/JeroenVinke/aurelia-computed-bug

Is this something that can be fixed? My use-case involves breeze like this:

```
get isNew() {
  return this.entity && this.entity.entityAspect.entityState.isAdded();
}
```

**Comment by jdanyow** [comment]
I think this has to do with a bug in Aurelia's AST logic where it doesn't short-circuit evaluation of expressions.  What's happening is the binding system is evaluating the right-hand side of the `&&` expression even when `this.entity` is falsy.  We're planning on fixing this after the binding refactor.

https://github.com/aurelia/binding/issues/116

**Comment by JeroenVinke** [comment]
Yes, that looks like it's the same issue. I can work around this for a while.
