### ISSUE TITLE
update to the latest releases

### ISSUE THREAD

**Issue by JeroenVinke** [jdanyow/aurelia-computed#9]
I'm sure you will get to this eventually, but created an issue anyway for visibility :smile:

**Comment by JeroenVinke** [comment]
I have tried to update it myself, but hit this unit test error:

```
TypeError: binding.observeProperty is not a function
            at AccessScope.connect (D:/Development/aurelia-computed/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1051:15)
            at AccessMember.connect (D:/Development/aurelia-computed/jspm_packages/github/aurelia/binding@0.10.0/aurelia-binding.js:1093:19)
            at GetterObserver.subscribe (D:/Development/aurelia-computed/src/getter-observer.js:38:40)
            at Object.<anonymous> (D:/Development/aurelia-computed/test/adapter.spec.js:176:20)
Chrome 46.0.2490 (Windows 10 0.0.0): Executed 7 of 7 (1 FAILED) (0.034 secs / 0.018 secs)
```

this is after updating the libs, and installing aurelia-pal as you've mentioned [here](https://github.com/aurelia/http-client/issues/106#issuecomment-147775802).

**Comment by jdanyow** [comment]
@JeroenVinke I'll try to get to this tonight or during my lunch-break today- it's tricky because the binding system has been overhauled in this release

**Comment by JeroenVinke** [comment]
Just tried it out, works like a charm!  Thanks!
